import { useState } from 'react';
import { Shield, AlertTriangle, CheckCircle, Search, Loader2, Copy, RotateCcw, Link, Mail } from 'lucide-react';
import { analyzePhishing, PhishingAnalysis } from '../../lib/aiService';

export default function PhishingDetector() {
  const [input, setInput] = useState('');
  const [inputType, setInputType] = useState<'url' | 'email'>('url');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<PhishingAnalysis | null>(null);
  const [copied, setCopied] = useState(false);

  const analyze = async () => {
    if (!input.trim()) return;
    setLoading(true);
    setResult(null);
    const res = await analyzePhishing(input.trim());
    setResult(res);
    setLoading(false);
  };

  const reset = () => { setInput(''); setResult(null); };

  const copyReport = () => {
    if (!result) return;
    const text = `CyberSafe Phishing Report\n${'='.repeat(30)}\nInput: ${input}\nVerdict: ${result.verdict.toUpperCase()}\nThreat Score: ${result.threatScore}/100\nCategory: ${result.category}\n\nRed Flags:\n${result.redFlags.map(f => `• ${f}`).join('\n')}\n\nExplanation: ${result.explanation}\n\nRecommendation: ${result.recommendation}\n\nGenerated by CyberSafe AI Portal | Helpline: 1930`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const verdictConfig = result ? {
    safe: { color: '#34d399', bg: 'rgba(52,211,153,0.08)', border: 'rgba(52,211,153,0.2)', icon: CheckCircle, label: 'SAFE', desc: 'No threats detected' },
    suspicious: { color: '#f59e0b', bg: 'rgba(245,158,11,0.08)', border: 'rgba(245,158,11,0.2)', icon: AlertTriangle, label: 'SUSPICIOUS', desc: 'Potential threat detected' },
    dangerous: { color: '#ef4444', bg: 'rgba(239,68,68,0.08)', border: 'rgba(239,68,68,0.2)', icon: Shield, label: 'DANGEROUS', desc: 'High threat confirmed' },
  }[result.verdict] : null;

  return (
    <div className="p-6 lg:p-8 max-w-3xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 rounded-lg flex items-center justify-center" style={{ background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.2)' }}>
            <Shield className="w-5 h-5 text-red-400" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white font-display tracking-wider">PHISHING DETECTOR</h1>
            <p className="text-[10px] font-mono tracking-widest" style={{ color: 'rgba(56,189,248,0.4)' }}>AI-POWERED THREAT ANALYSIS · GEMINI</p>
          </div>
        </div>
        <p className="text-slate-400 text-sm mt-2">Paste a suspicious URL or email text and our AI will analyze it for phishing, scam, or malware indicators.</p>
      </div>

      {/* Input Card */}
      <div className="rounded-xl border p-6 mb-6" style={{ background: 'rgba(10,22,40,0.6)', borderColor: 'rgba(56,189,248,0.1)' }}>
        {/* Type Toggle */}
        <div className="flex gap-2 mb-4">
          {(['url', 'email'] as const).map(t => (
            <button
              key={t}
              onClick={() => setInputType(t)}
              className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-mono transition-all"
              style={inputType === t
                ? { background: 'rgba(56,189,248,0.12)', color: 'var(--cyber-blue)', border: '1px solid rgba(56,189,248,0.3)' }
                : { background: 'transparent', color: '#475569', border: '1px solid rgba(56,189,248,0.06)' }}
            >
              {t === 'url' ? <Link className="w-3.5 h-3.5" /> : <Mail className="w-3.5 h-3.5" />}
              {t.toUpperCase()}
            </button>
          ))}
        </div>

        <textarea
          value={input}
          onChange={e => setInput(e.target.value)}
          placeholder={inputType === 'url'
            ? 'Paste suspicious URL here...\ne.g. https://hdfc-bank-secure-login.xyz/verify'
            : 'Paste suspicious email text here...\ne.g. "Dear customer, your account will be suspended. Click here to verify..."'}
          rows={4}
          className="w-full rounded-lg px-4 py-3 text-sm font-mono text-white placeholder-slate-600 outline-none resize-none border transition-all focus:border-[rgba(56,189,248,0.3)]"
          style={{ background: 'rgba(6,14,26,0.8)', borderColor: 'rgba(56,189,248,0.1)' }}
        />

        <div className="flex gap-3 mt-4">
          <button
            onClick={analyze}
            disabled={!input.trim() || loading}
            className="flex items-center gap-2 px-6 py-2.5 rounded-lg font-semibold text-sm transition-all disabled:opacity-40"
            style={{ background: 'linear-gradient(135deg, #0ea5e9, #0284c7)', color: 'white', boxShadow: '0 0 20px rgba(56,189,248,0.2)' }}
          >
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Search className="w-4 h-4" />}
            {loading ? 'ANALYZING...' : 'ANALYZE THREAT'}
          </button>
          {result && (
            <button onClick={reset} className="flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm transition-all" style={{ background: 'rgba(56,189,248,0.06)', color: '#64748b', border: '1px solid rgba(56,189,248,0.08)' }}>
              <RotateCcw className="w-4 h-4" />
              Reset
            </button>
          )}
        </div>
      </div>

      {/* Loading */}
      {loading && (
        <div className="rounded-xl border p-8 text-center" style={{ background: 'rgba(10,22,40,0.6)', borderColor: 'rgba(56,189,248,0.1)' }}>
          <div className="relative w-16 h-16 mx-auto mb-4">
            <div className="absolute inset-0 rounded-full border-2 animate-spin" style={{ borderColor: 'rgba(56,189,248,0.1)', borderTopColor: 'var(--cyber-blue)' }} />
            <div className="absolute inset-3 rounded-full border animate-ping" style={{ borderColor: 'rgba(239,68,68,0.3)' }} />
          </div>
          <p className="font-mono text-sm" style={{ color: 'var(--cyber-blue)' }}>SCANNING FOR THREATS<span className="animate-pulse">...</span></p>
          <p className="text-xs text-slate-600 mt-1 font-mono">Gemini AI analyzing patterns</p>
        </div>
      )}

      {/* Result */}
      {result && verdictConfig && (
        <div className="space-y-4">
          {/* Verdict Banner */}
          <div className="rounded-xl border p-5 flex items-center gap-4" style={{ background: verdictConfig.bg, borderColor: verdictConfig.border }}>
            <div className="w-14 h-14 rounded-full flex items-center justify-center flex-shrink-0" style={{ background: verdictConfig.bg, border: `2px solid ${verdictConfig.color}` }}>
              <verdictConfig.icon className="w-7 h-7" style={{ color: verdictConfig.color }} />
            </div>
            <div className="flex-1">
              <p className="text-lg font-bold font-mono" style={{ color: verdictConfig.color }}>{verdictConfig.label}</p>
              <p className="text-slate-400 text-sm">{verdictConfig.desc}</p>
            </div>
            {/* Threat Gauge */}
            <div className="text-center">
              <p className="text-3xl font-bold font-display" style={{ color: verdictConfig.color }}>{result.threatScore}</p>
              <p className="text-[10px] font-mono text-slate-500 tracking-wider">THREAT SCORE</p>
              <div className="w-24 h-1.5 rounded-full mt-1 overflow-hidden" style={{ background: 'rgba(255,255,255,0.1)' }}>
                <div className="h-full rounded-full transition-all" style={{ width: `${result.threatScore}%`, background: verdictConfig.color }} />
              </div>
            </div>
          </div>

          {/* Red Flags */}
          {result.redFlags.length > 0 && (
            <div className="rounded-xl border p-5" style={{ background: 'rgba(10,22,40,0.6)', borderColor: 'rgba(56,189,248,0.1)' }}>
              <h3 className="text-sm font-mono font-semibold text-white mb-3 flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-red-400" />
                RED FLAGS DETECTED
              </h3>
              <ul className="space-y-2">
                {result.redFlags.map((flag, i) => (
                  <li key={i} className="flex items-start gap-2.5 text-sm">
                    <AlertTriangle className="w-4 h-4 text-red-400 flex-shrink-0 mt-0.5" />
                    <span className="text-slate-300">{flag}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Explanation & Recommendation */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="rounded-xl border p-5" style={{ background: 'rgba(10,22,40,0.6)', borderColor: 'rgba(56,189,248,0.1)' }}>
              <h3 className="text-xs font-mono font-semibold mb-2" style={{ color: 'rgba(56,189,248,0.6)' }}>AI ANALYSIS</h3>
              <p className="text-slate-300 text-sm leading-relaxed">{result.explanation}</p>
            </div>
            <div className="rounded-xl border p-5" style={{ background: 'rgba(10,22,40,0.6)', borderColor: 'rgba(52,211,153,0.1)' }}>
              <h3 className="text-xs font-mono font-semibold mb-2" style={{ color: 'rgba(52,211,153,0.6)' }}>RECOMMENDED ACTION</h3>
              <p className="text-slate-300 text-sm leading-relaxed">{result.recommendation}</p>
              <p className="text-xs font-mono mt-3" style={{ color: 'rgba(52,211,153,0.5)' }}>📞 Cybercrime Helpline: 1930</p>
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-3">
            <button onClick={copyReport} className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm transition-all" style={{ background: 'rgba(56,189,248,0.06)', color: copied ? '#34d399' : '#64748b', border: '1px solid rgba(56,189,248,0.08)' }}>
              <Copy className="w-4 h-4" />
              {copied ? 'Copied!' : 'Copy Report'}
            </button>
            <a href="/dashboard/report" className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm transition-all" style={{ background: 'rgba(239,68,68,0.08)', color: '#ef4444', border: '1px solid rgba(239,68,68,0.2)' }}>
              <Shield className="w-4 h-4" />
              Report This Incident
            </a>
          </div>
        </div>
      )}
    </div>
  );
}
